# Generated by Django 5.0.3 on 2024-05-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_Sale',
            new_name='is_sale',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Sale_price',
            new_name='sale_price',
        ),
    ]
